# Generated by Django 4.2.5 on 2023-12-01 07:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CardImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Card Image/')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(blank=True, max_length=100, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('required', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IconMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=200)),
                ('icon_svg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_submenu_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.project')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('use_checkbox', models.BooleanField(default=False)),
                ('use_date', models.BooleanField(default=False)),
                ('use_autonow', models.BooleanField(default=False)),
                ('use_file_upload', models.BooleanField(default=False)),
                ('file_upload_limit', models.IntegerField(blank=True, null=True)),
                ('max_digits', models.IntegerField(blank=True, null=True)),
                ('decimal_places', models.IntegerField(blank=True, null=True)),
                ('select_db_table', models.CharField(blank=True, max_length=100, null=True)),
                ('protocol', models.CharField(blank=True, max_length=100, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('allow_markdown', models.BooleanField(default=False)),
                ('use_seconds', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.project')),
            ],
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(max_length=20)),
                ('properties', models.JSONField()),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('args', models.ForeignKey(help_text='*args', null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.argument')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.table')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_menu_name', models.CharField(blank=True, max_length=250, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.mainsubmenu')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.project')),
                ('screen_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(max_length=200)),
                ('button_color', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Grey'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Orange'), ('info', 'SkyBlue'), ('light', 'Light'), ('dark', 'Dark')], max_length=20)),
                ('modal_size', models.CharField(choices=[('sm', 'Small'), ('lg', 'Large'), ('xl', 'Extra Large')], max_length=20)),
                ('modal_color', models.CharField(max_length=200)),
                ('modal_title', models.CharField(max_length=100)),
                ('modal_description_type', models.CharField(max_length=100)),
                ('modal_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('formtable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.table')),
                ('screen_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(blank=True, max_length=250, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.project')),
                ('screen_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_size', models.IntegerField(default='12', help_text='Use a number from 1 to 12, e.g., 6')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('password', 'Password'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('number', 'Number'), ('email', 'Email'), ('url', 'URL'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and Time'), ('month', 'Month and Year'), ('week', 'Week'), ('search', 'Search'), ('tel', 'Telephone'), ('color', 'Color'), ('file', 'File Upload'), ('hidden', 'Hidden'), ('range', 'Range'), ('submit', 'Submit Button'), ('reset', 'Reset Button'), ('button', 'Generic Button'), ('image', 'Image Button'), ('datetime-local', 'Date and Time (Local)'), ('month', 'Month')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('disabled', models.BooleanField(blank=True, null=True)),
                ('readonly', models.BooleanField(blank=True, null=True)),
                ('required', models.BooleanField(blank=True, null=True)),
                ('autofocus', models.BooleanField(blank=True, null=True)),
                ('max', models.CharField(blank=True, max_length=255, null=True)),
                ('min', models.CharField(blank=True, max_length=255, null=True)),
                ('maxlength', models.PositiveIntegerField(blank=True, null=True)),
                ('minlength', models.PositiveIntegerField(blank=True, null=True)),
                ('step', models.CharField(blank=True, max_length=255, null=True)),
                ('pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('accept', models.CharField(blank=True, max_length=255, null=True)),
                ('multiple', models.BooleanField(blank=True, null=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('list', models.CharField(blank=True, max_length=255, null=True)),
                ('autocomplete', models.CharField(blank=True, max_length=255, null=True)),
                ('spellcheck', models.BooleanField(blank=True, null=True)),
                ('autocorrect', models.CharField(blank=True, max_length=255, null=True)),
                ('autocapitalize', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
            ],
        ),
        migrations.CreateModel(
            name='FormWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_size', models.IntegerField(default='12', help_text='Use number from 1 to 12 eg:6')),
                ('heading', models.CharField(max_length=250)),
                ('formtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.table')),
                ('screen_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.field')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.table')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.table'),
        ),
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Grey'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Orange'), ('info', 'SkyBlue'), ('light', 'Light'), ('dark', 'Dark')], max_length=20)),
                ('button_name', models.CharField(max_length=100)),
                ('dropdown_item_name', models.CharField(max_length=100)),
                ('screen_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_number', models.IntegerField(default='12', help_text='Use number from 1 to 12 eg:6')),
                ('color_code', models.CharField(max_length=20)),
                ('card_title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('screen_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_type', models.CharField(choices=[('button', 'Button'), ('submit', 'Submit')], max_length=20)),
                ('color_code', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Grey'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Orange'), ('info', 'SkyBlue'), ('light', 'Light'), ('dark', 'Dark')], max_length=20)),
                ('button_name', models.CharField(max_length=50)),
                ('screen_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Grey'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Orange'), ('info', 'SkyBlue'), ('light', 'Light'), ('dark', 'Dark')], max_length=20)),
                ('message', models.CharField(max_length=250)),
                ('screen_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
            ],
        ),
        migrations.CreateModel(
            name='A_Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_link', models.CharField(max_length=250)),
                ('color_code', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Grey'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Orange'), ('info', 'SkyBlue'), ('light', 'Light'), ('dark', 'Dark')], max_length=20)),
                ('button_name', models.CharField(max_length=50)),
                ('screen_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
            ],
        ),
    ]
