# Generated by Django 4.2.7 on 2023-12-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sub_part", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_version_name", models.CharField(max_length=100)),
                ("is_checked", models.BooleanField(default=False)),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sub_part.field",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sub_part.formwidget",
                    ),
                ),
            ],
        ),
    ]
