# Generated by Django 4.2.5 on 2023-12-06 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_remove_field_field_name_remove_field_field_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='allow_markdown',
        ),
        migrations.RemoveField(
            model_name='field',
            name='file_upload_limit',
        ),
        migrations.RemoveField(
            model_name='field',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='field',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='field',
            name='select_db_table',
        ),
        migrations.RemoveField(
            model_name='field',
            name='use_autonow',
        ),
        migrations.RemoveField(
            model_name='field',
            name='use_checkbox',
        ),
        migrations.RemoveField(
            model_name='field',
            name='use_date',
        ),
        migrations.RemoveField(
            model_name='field',
            name='use_file_upload',
        ),
        migrations.RemoveField(
            model_name='field',
            name='use_seconds',
        ),
        migrations.RemoveField(
            model_name='table',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='table',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='table',
            name='required',
        ),
        migrations.AddField(
            model_name='field',
            name='allow_markdown_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='auto_now_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='date_format',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='field_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='file_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='ip_protocol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='many_to_many',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mamy_to_many_field', to='sub_part.table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='one_to_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='one_to_one_field', to='sub_part.table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='table_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Table_name_field', to='sub_part.table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='use_seconds_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='help_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.project'),
        ),
    ]
