# Generated by Django 4.2.5 on 2023-12-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_remove_field_allow_markdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='allow_markdown_checkbox',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='auto_now_checkbox',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='use_seconds_checkbox',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
