# Generated by Django 4.2.5 on 2023-12-06 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_alter_field_allow_markdown_checkbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='many_to_many',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mamy_to_many_field', to='sub_part.table'),
        ),
        migrations.AlterField(
            model_name='field',
            name='one_to_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_to_one_field', to='sub_part.table'),
        ),
        migrations.AlterField(
            model_name='field',
            name='table_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Table_name_field', to='sub_part.table'),
        ),
    ]
