# Generated by Django 4.2.7 on 2023-12-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_alter_screen_project'),
        ('sub_part', '0006_alter_field_many_to_many_alter_field_one_to_one_and_more'),
    ]

    operations = [
    ]
