# Generated by Django 4.2.7 on 2023-12-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_merge_20231207_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldsize', models.CharField(blank=True, max_length=12, null=True)),
                ('fieldname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.field')),
                ('formwidget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.formwidget')),
                ('screen_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
                ('tablename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.table')),
            ],
        ),
    ]
