# Generated by Django 4.2.8 on 2023-12-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_alter_project_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
    ]
