# Generated by Django 4.2.8 on 2023-12-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_remove_project_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verion_name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.project')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.screen')),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_part.project')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenVersionFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.field')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.screenversion')),
            ],
        ),
        migrations.AddField(
            model_name='screenversion',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.usertypemaster'),
        ),
    ]
