# Generated by Django 4.2.7 on 2023-12-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_screenversion_usertypemaster_screenversionfields_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='allow_markdown_checkbox',
            new_name='boolean_checkbox',
        ),
    ]
