# Generated by Django 4.2.8 on 2023-12-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_screenversion_usertypemaster_screenversionfields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenversionfields',
            name='column_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screenversionfields',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
