# Generated by Django 4.2.8 on 2023-12-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_screenversionfields_label_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenversion',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
