# Generated by Django 4.2.7 on 2023-12-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0012_rename_allow_markdown_checkbox_field_boolean_checkbox'),
        ('sub_part', '0015_alter_screenversion_status'),
    ]

    operations = [
    ]
