# Generated by Django 4.2.7 on 2024-02-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0016_merge_20231226_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(blank=True, max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('model_type', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_name', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_part.project')),
            ],
        ),
    ]
